### ISSUE TITLE
[CSS] Update UI

### ISSUE THREAD

**Issue by Sanket1308** [Sanket1308/website-authentication-process#2]
- Use your creativity

**Comment by Amarjit-Khan** [comment]
Hey, can I solve this issue?

**Comment by Sanket1308** [comment]
Go ahead! Contribute well🚀

**Comment by Amarjit-Khan** [comment]
![Screenshot 2022-10-03 085301](https://user-images.githubusercontent.com/98657673/193496369-75e9d85c-925d-47f1-8e20-d3c55e48f274.png)

Please can you help resolve this issue.

**Comment by akshit5565** [comment]
@Sanket1308  Can i work on this issue??

**Comment by Sanket1308** [comment]
What changes will you work on? @akshit5565

**Comment by akshit5565** [comment]
> What changes will you work on? @akshit5565

Improvement in UI , giving more of a professional look

**Comment by Sanket1308** [comment]
Go ahead @akshit5565 ! Contribute well🚀

**Comment by akshit5565** [comment]
> Go ahead @akshit5565 ! Contribute well🚀

Thank you !!!
I am starting my work!!

**Comment by akshit5565** [comment]
@Sanket1308  Can i work on this or not , as the issue is closed??
