### ISSUE TITLE
hacktoberfest label

### ISSUE THREAD

**Issue by hairullana** [Sanket1308/website-authentication-process#30]
Maybe it's not an issue about your code, but you have a typo on label from **`hactoberfest`** should be **`hacktoberfest`** (with K on hack word)
![image](https://user-images.githubusercontent.com/56705867/195006147-d3165e60-9509-4a96-98f5-1cfc9ac54e38.png)

Because the hacktoberfest official website announce this to me, thank you
![image](https://user-images.githubusercontent.com/56705867/195006187-baa17f3c-147d-4498-b8fb-828427d53731.png)

**Comment by Sanket1308** [comment]
Corrected! Thank you🚀
