### ISSUE TITLE
Update CONTRIBUTING.md file

### ISSUE THREAD

**Issue by Sanket1308** [Sanket1308/website-authentication-process#4]

**Comment by rahulssv** [comment]
#11 
Added CONTRIBUTORS.md file

**Comment by arpanaditya** [comment]
Hey @Sanket1308 , can I work on this issue? I will add `how to contribute` section here.

**Comment by prnvtripathi** [comment]
Hey @Sanket1308, i can contribute in upgrading the contributions.md file.
I can add `prerequisites` and `how to contribute` sections

**Comment by Sanket1308** [comment]
@arpanaditya add how to contribute section
@prnvtripathi add prerequisites section
