### ISSUE TITLE
[HTML] Add a favicon

### ISSUE THREAD

**Issue by Sanket1308** [Sanket1308/website-authentication-process#7]
[HTML] Add a favicon
- Design must be related to 'S' letter
- Keep background transparent
- Send design here in discussion before creating PR

**Comment by satyamrs00** [comment]
<img width="76" alt="image" src="https://user-images.githubusercontent.com/96380323/193454746-5bd9d04c-3062-43e5-b3e8-42c9be5f20c2.png">
How is this ? 
Its red, so its clearly visible

**Comment by Sanket1308** [comment]
Could be better!

**Comment by satyamrs00** [comment]
<img width="253" alt="image" src="https://user-images.githubusercontent.com/96380323/193456075-c476f1bf-35ce-46f8-9011-7e6a3e82d93a.png">
Any one of these ?

**Comment by Sanket1308** [comment]
![icons8-schoology-32](https://user-images.githubusercontent.com/79108273/193457387-7104c5a0-6ff0-428c-b7f2-d308f87045f4.png)
 Use this
